require("conf.variables")
require("conf.decorations")
require("conf.env")
require("conf.autostart")
require("conf.monitors")
require("conf.layout")
require("conf.workspaces")
require("conf.windowrules")
require("conf.bindings")
require("conf.input")
require("conf.animations")

-- Theme colors from theme-switch (overrides the borders in conf/decorations)
pcall(dofile, os.getenv("HOME") .. "/.local/state/theme/current/hyprland.lua")
