require("fzf-lua").setup({
	files = {
		fd_opts = "--exclude node_modules --exclude .git",
	},
	grep = {
		rg_opts = "--glob '!node_modules' --column --line-number --no-heading --color=always --smart-case --max-columns=4096",
	},
})
require("fzf-lua").register_ui_select()

vim.keymap.set("n", "<leader>ff", function()
	require("fzf-lua").files()
end, { desc = "[F]ind [F]iles" })
vim.keymap.set("n", "<leader>fg", function()
	require("fzf-lua").live_grep()
end, { desc = "[F]ind [G]rep" })
vim.keymap.set("n", "<leader>fc", function()
	require("fzf-lua").files({ cwd = vim.fn.stdpath("config") })
end, { desc = "[F]ind [C]onfig" })
vim.keymap.set("n", "<leader>fh", function()
	require("fzf-lua").helptags()
end, { desc = "[F]ind [H]elp" })
vim.keymap.set("n", "<leader>fk", function()
	require("fzf-lua").keymaps()
end, { desc = "[F]ind [K]eymaps" })
vim.keymap.set("n", "<leader>fb", function()
	require("fzf-lua").builtin()
end, { desc = "[F]ind [B]uiltins FZF" })
vim.keymap.set("n", "<leader>fw", function()
	require("fzf-lua").grep_cword()
end, { desc = "[F]ind current [w]ord" })
vim.keymap.set("n", "<leader>fW", function()
	require("fzf-lua").grep_cWORD()
end, { desc = "[F]ind current [W]ord" })
vim.keymap.set("n", "<leader>fd", function()
	require("fzf-lua").diagnostics_document()
end, { desc = "[F]ind [D]iagnostics" })
vim.keymap.set("n", "<leader>fr", function()
	require("fzf-lua").resume()
end, { desc = "[F]ind [R]esume" })
vim.keymap.set("n", "<leader>fo", function()
	require("fzf-lua").oldfiles()
end, { desc = "[F]ind [O]ld Files" })
vim.keymap.set("n", "<leader><leader>", function()
	require("fzf-lua").buffers()
end, { desc = "[,] Find existing buffers" })
vim.keymap.set("n", "<leader>/", function()
	require("fzf-lua").lgrep_curbuf()
end, { desc = "[/] Live grep the current buffer" })
